### PR TITLE
Updating graphql dependency

### PR DESCRIPTION
**Pull request by D1plo1d**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks fine to me. Can you explain why it's important to make it less than version 15?

**Comment by D1plo1d** [comment]
@RichardLitt in SemVer version 15 would be the next version that could introduce any breaking changes that could cause incompatibility with graphql-scalars. I would wait until a version 15 is released to assess whether we can increase the version or need to patch for 15.x compatibility.

**Comment by cfnelson** [comment]
@D1plo1d Have you tested this using graphql 14.0.2 as there were significant changes to graphql spec and implementation. Unsure if this would/will effect this pkg though, as we've not had any time to investigate.

**Comment by ccuilla** [comment]
We'll fix this in v0.4.3 coming shortly.

**Comment by D1plo1d** [comment]
@ccuilla Awesome, thanks!

@cfnelson re: testing: no, nothing comprehensive. I've only used it with the DateTime type so far.

**Comment by ccuilla** [comment]
Updated in v0.4.3.

**Pull request closed without merging**
