### PR TITLE
update packages and add yarn.lock

### PR DESCRIPTION
**Pull request by OlivierCo**
- update outdated packages
- use yarn

### CODE REVIEW

**Comment by pauldowman** [comment]
It's a busy week here with everyone finishing things up right before the holidays, but we will take a look ASAP! Thanks!

**Comment by OlivierCo** [comment]
Happy new year guys!!!
Any thoughts on this one guys?

**Comment by ccuilla** [comment]
We'll fix this in v0.4.3 coming shortly.

**Comment by ccuilla** [comment]
Updated and added in v0.4.3.

**Pull request closed without merging**
