### PR TITLE
adds a typescript definition file and bumps deps

### LINKED ISSUE #19: Could not find a declaration file for module '@okgrow/graphql-scalars'.
Following steps in README gets me to a point where I get the following error

    [ts]
    Could not find a declaration file for module '@okgrow/graphql-scalars'.  '/Users/<user>/<appPath>/node_modules/@okgrow/graphql-scalars/index.js' implicitly has an 'any' type.
      Try `npm install @types/okgrow__graphql-scalars` if it exists or add a new declaration (.d.ts) file containing `declare module '@okgrow/graphql-scalars';` [7016]

I tried `npm install @types/okgrow__graphql-scalars` but get error Not Found- probably an oversight on my part but can't pin it down.

Any ideas?

### PR DESCRIPTION
**Pull request by capaj**
fixes #19

### CODE REVIEW

**Comment by capaj** [comment]
@ccuilla you've marked the issue as help wanted in the issue thread so here I am trying to fix it.

**Comment by ccuilla** [comment]
@capaj So I went with what you had in `graphql-scalars.d.ts` which is different from @luvies comment above. The one in `graphql-scalars.d.ts` seems to be breaking some builds. When I try the one above I get an error that "a declare modifier is required for a top level declaration in a d.ts file".

I'm not familiar with TS, so I'm not sure what the right structure for this file needs to be. Either of you have a suggestion?

**Comment by capaj** [comment]
@ccuilla I mostly use TS in the library itself and let typescript generate `d.ts` for me so I am not sure what could be breaking some builds. Is this related to any issues reported? What error is typescript compiler showing?

@luvies's file is probably just missing a `declare` keyword. Also I am a bit confused about the last part after `const def: {`

**Comment by ccuilla** [comment]
The report issue is this: https://github.com/okgrow/graphql-scalars/issues/32

One thing I noticed that I missed is that in `graphql-scalars.d.ts` line 14 appears to be a duplicate of line 4. Besides that my linter is now complaining about the `declares` on lines 4-17, 19 with "A 'declare' modifier cannot be used in an already ambient context".

Should these just be removed this this:

```ts
import { GraphQLScalarType } from 'graphql';

declare namespace GraphqlScalars {
  const EmailAddress: GraphQLScalarType;
  const DateTime: GraphQLScalarType;
  const NonPositiveInt: GraphQLScalarType;
  const PositiveInt: GraphQLScalarType;
  const NonNegativeInt: GraphQLScalarType;
  const NegativeInt: GraphQLScalarType;
  const NonPositiveFloat: GraphQLScalarType;
  const PositiveFloat: GraphQLScalarType;
  const NonNegativeFloat: GraphQLScalarType;
  const NegativeFloat: GraphQLScalarType;
  const URL: GraphQLScalarType;
  const PhoneNumber: GraphQLScalarType;
  const PostalCode: GraphQLScalarType;

  class RegularExpression extends GraphQLScalarType {
    constructor(name: string, regex: RegExp);
  }
}

export = GraphqlScalars;
```

**Comment by capaj** [comment]
yep I was copying it from https://github.com/okgrow/graphql-scalars/issues/19#issuecomment-450758891 and @[vkykv](/vkykv) had mistake there.

Correct definition should be:
```ts
import { GraphQLScalarType } from 'graphql';

declare namespace GraphqlScalars {
  const EmailAddress: GraphQLScalarType;
  const DateTime: GraphQLScalarType;
  const NonPositiveInt: GraphQLScalarType;
  const PositiveInt: GraphQLScalarType;
  const NonNegativeInt: GraphQLScalarType;
  const NegativeInt: GraphQLScalarType;
  const NonPositiveFloat: GraphQLScalarType;
  const PositiveFloat: GraphQLScalarType;
  const NonNegativeFloat: GraphQLScalarType;
  const NegativeFloat: GraphQLScalarType;
  const URL: GraphQLScalarType;
  const PhoneNumber: GraphQLScalarType;
  const PostalCode: GraphQLScalarType;

  class RegularExpression extends GraphQLScalarType {
    constructor(name: string, regex: RegExp);
  }

  const DateTimeScalar: string;
  const NonPositiveIntScalar: string;
  const PositiveIntScalar: string;
  const NonNegativeIntScalar: string;
  const UnsignedIntScalar: string;
  const NegativeIntScalar: string;
  const NonPositiveFloatScalar: string;
  const PositiveFloatScalar: string;
  const NonNegativeFloatScalar: string;
  const UnsignedFloatScalar: string;
  const NegativeFloatScalar: string;
  const EmailAddressScalar: string;
  const URLScalar: string;
  const PhoneNumberScalar: string;
  const PostalCodeScalar: string;
  const RegularExpressionScalar: string;
  const OKGScalarDefinitions: string[];
}

export = GraphqlScalars;

```

**Comment by ccuilla** [comment]
Thanks guys! I'm going with this:

```ts
import { GraphQLScalarType } from 'graphql';

interface RegularExpressionOptions {
  errorMessage: Function;
}
declare namespace GraphqlScalars {
  const EmailAddress: GraphQLScalarType;
  const DateTime: GraphQLScalarType;
  const NonPositiveInt: GraphQLScalarType;
  const PositiveInt: GraphQLScalarType;
  const NonNegativeInt: GraphQLScalarType;
  const NegativeInt: GraphQLScalarType;
  const NonPositiveFloat: GraphQLScalarType;
  const PositiveFloat: GraphQLScalarType;
  const NonNegativeFloat: GraphQLScalarType;
  const NegativeFloat: GraphQLScalarType;
  const URL: GraphQLScalarType;
  const PhoneNumber: GraphQLScalarType;
  const PostalCode: GraphQLScalarType;

  class RegularExpression extends GraphQLScalarType {
    constructor(
      name: string,
      regex: RegExp,
      options?: RegularExpressionOptions,
    );
  }

  const DateTimeScalar: string;
  const NonPositiveIntScalar: string;
  const PositiveIntScalar: string;
  const NonNegativeIntScalar: string;
  const UnsignedIntScalar: string;
  const NegativeIntScalar: string;
  const NonPositiveFloatScalar: string;
  const PositiveFloatScalar: string;
  const NonNegativeFloatScalar: string;
  const UnsignedFloatScalar: string;
  const NegativeFloatScalar: string;
  const EmailAddressScalar: string;
  const URLScalar: string;
  const PhoneNumberScalar: string;
  const PostalCodeScalar: string;
  const RegularExpressionScalar: string;
  const OKGScalarDefinitions: string[];
}

export = GraphqlScalars;
```

**Comment by luvies** [comment]
@capaj The `const def: {` bit was to set up the default exports, since this package does provide them, so they need to be typed. Probably could have done a different name, though. 

@ccuilla I think @capaj had the more correct definition, since the package actually does the exports properly as ES6 ones, so making it a namespace and doing `export = GraphqlScalars` doesn't quite line up with how it's actually implemented. If you were doing it to make the default export work properly, then it is actually incorrect, since the default export doesn't export everything, only the scalar objects.

**Pull request merged**
